<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Raygui-cs-creeperlv" Version="1.0.0" />
      <PackageReference Include="Raylib-cs" Version="7.0.2" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Textures\" />
    </ItemGroup>

    <ItemGroup>
      <None Update="Texturas\CartaVirusVerde.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\VirusVerde.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\VirusRojo.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\VirusComodin.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\VirusAzul.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\VirusAmarillo.jpg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\Transplante.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\Robo.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\ParteAtras.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\OrganoVerde.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\OrganoRojo.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\OrganoComodin.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\OrganoAzul.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\OrganoAmarillo.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\Error.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\Descarte.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\CuraVerde.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\CuraComodin.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\CuraRoja.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\CuraAzul.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\CuraAmarilla.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\Contagio.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\Contagio.jpg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\CuraAmarilla.jpg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\CuraAzul.jpg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\CuraComodin.jpg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\CuraRoja.jpg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\CuraVerde.jpg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\Descarte.jpg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\Error.jpg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\OrganoAmarillo.jpg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\OrganoAzul.jpg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\OrganoComodin.jpg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\OrganoRojo.jpg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\OrganoVerde.jpg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\ParteAtras.jpg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\Robo.jpg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\Transplante.jpg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\VirusAzul.jpg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\VirusComodin.jpg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\VirusRojo.jpg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Texturas\VirusVerde.jpg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
